// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iGR3j33L5_L4V1yM3tDW-E4PdyuO86I',
    appId: '1:1050581332752:web:7aeae93351e243e9ae6b95',
    messagingSenderId: '1050581332752',
    projectId: 'cinema-be9a9',
    authDomain: 'cinema-be9a9.firebaseapp.com',
    storageBucket: 'cinema-be9a9.appspot.com',
    measurementId: 'G-939BBC6H2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAfnBv_F6GVJC1MBIvADY8qNGl9VP4Abw',
    appId: '1:1050581332752:android:886580f2c91c6c9dae6b95',
    messagingSenderId: '1050581332752',
    projectId: 'cinema-be9a9',
    storageBucket: 'cinema-be9a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArCp4-bX4p6yvvmuGJFysr9AeRA8wtbiU',
    appId: '1:1050581332752:ios:d547aa9f0138501aae6b95',
    messagingSenderId: '1050581332752',
    projectId: 'cinema-be9a9',
    storageBucket: 'cinema-be9a9.appspot.com',
    iosBundleId: 'com.example.cinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArCp4-bX4p6yvvmuGJFysr9AeRA8wtbiU',
    appId: '1:1050581332752:ios:d547aa9f0138501aae6b95',
    messagingSenderId: '1050581332752',
    projectId: 'cinema-be9a9',
    storageBucket: 'cinema-be9a9.appspot.com',
    iosBundleId: 'com.example.cinema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3iGR3j33L5_L4V1yM3tDW-E4PdyuO86I',
    appId: '1:1050581332752:web:83fce3e84057ab41ae6b95',
    messagingSenderId: '1050581332752',
    projectId: 'cinema-be9a9',
    authDomain: 'cinema-be9a9.firebaseapp.com',
    storageBucket: 'cinema-be9a9.appspot.com',
    measurementId: 'G-6FLRVSQC22',
  );
}
